"""empty message

Revision ID: 07129a2d8d68
Revises: 2b1f9b7eb4e6
Create Date: 2018-12-30 11:45:11.510646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07129a2d8d68'
down_revision = '2b1f9b7eb4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('model_number', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('name', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('nbg_code', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('x_ray', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('ra', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('rv', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('detach', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('n_bos', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('n_rrt', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('m_bos', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('m_rrt', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('rrt_behaviour', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('rrt_longevity', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipg')
    # ### end Alembic commands ###
