"""empty message

Revision ID: 88fcc6308450
Revises: 
Create Date: 2019-01-07 12:07:38.336076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fcc6308450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crtd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('nbg_code', sa.String(length=255), nullable=True),
    sa.Column('x_ray', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('ra', sa.String(length=255), nullable=True),
    sa.Column('rv', sa.String(length=255), nullable=True),
    sa.Column('lv', sa.String(length=255), nullable=True),
    sa.Column('hv', sa.String(length=255), nullable=True),
    sa.Column('detach', sa.String(length=255), nullable=True),
    sa.Column('wave', sa.String(length=255), nullable=True),
    sa.Column('replacement', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crtp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('nbg_code', sa.String(length=255), nullable=True),
    sa.Column('x_ray', sa.String(length=255), nullable=True),
    sa.Column('ra', sa.String(length=255), nullable=True),
    sa.Column('la', sa.String(length=255), nullable=True),
    sa.Column('rv', sa.String(length=255), nullable=True),
    sa.Column('lv', sa.String(length=255), nullable=True),
    sa.Column('detach', sa.String(length=255), nullable=True),
    sa.Column('n_bol', sa.String(length=255), nullable=True),
    sa.Column('n_eri', sa.String(length=255), nullable=True),
    sa.Column('m_bol', sa.String(length=255), nullable=True),
    sa.Column('m_eri', sa.String(length=255), nullable=True),
    sa.Column('eri_behaviour', sa.String(length=255), nullable=True),
    sa.Column('longevity', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('sense', sa.String(length=255), nullable=True),
    sa.Column('high', sa.String(length=255), nullable=True),
    sa.Column('sensing', sa.String(length=255), nullable=True),
    sa.Column('lead', sa.String(length=255), nullable=True),
    sa.Column('placement', sa.String(length=255), nullable=True),
    sa.Column('fixation', sa.String(length=255), nullable=True),
    sa.Column('insulation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('nbg_code', sa.String(length=255), nullable=True),
    sa.Column('x_ray', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('ra', sa.String(length=255), nullable=True),
    sa.Column('rv', sa.String(length=255), nullable=True),
    sa.Column('hv', sa.String(length=255), nullable=True),
    sa.Column('detach', sa.String(length=255), nullable=True),
    sa.Column('wave', sa.String(length=255), nullable=True),
    sa.Column('replacement', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('nbg_code', sa.String(length=255), nullable=True),
    sa.Column('x_ray', sa.String(length=255), nullable=True),
    sa.Column('ra', sa.String(length=255), nullable=True),
    sa.Column('rv', sa.String(length=255), nullable=True),
    sa.Column('detach', sa.String(length=255), nullable=True),
    sa.Column('n_bos', sa.String(length=255), nullable=True),
    sa.Column('n_rrt', sa.String(length=255), nullable=True),
    sa.Column('m_bos', sa.String(length=255), nullable=True),
    sa.Column('m_rrt', sa.String(length=255), nullable=True),
    sa.Column('rrt_behaviour', sa.String(length=255), nullable=True),
    sa.Column('rrt_longevity', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('sense', sa.String(length=255), nullable=True),
    sa.Column('polarity', sa.String(length=255), nullable=True),
    sa.Column('fixation', sa.String(length=255), nullable=True),
    sa.Column('placement', sa.String(length=255), nullable=True),
    sa.Column('insulation', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('access', sa.String(length=5), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('lv')
    op.drop_table('ipg')
    op.drop_table('icd')
    op.drop_table('hv')
    op.drop_table('crtp')
    op.drop_table('crtd')
    # ### end Alembic commands ###
