"""empty message

Revision ID: dfd721865107
Revises: 23d5c5905d06
Create Date: 2018-12-30 17:00:13.778178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd721865107'
down_revision = '23d5c5905d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crtd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('model_number', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('name', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('nbg_code', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('x_ray', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('serial', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('ra', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('rv', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('lv', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('hv', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('detach', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('wave', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('replacement', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('model_number', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('name', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('serial', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('sense', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('high', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('sensing', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('lead', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('placement', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('fixation', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('insulation', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('model_number', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('name', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('nbg_code', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('x_ray', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('serial', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('ra', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('rv', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('hv', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('detach', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('wave', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('replacement', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('model_number', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('name', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('serial', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('sense', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('polarity', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('fixation', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('placement', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('insulation', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('location', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lv')
    op.drop_table('icd')
    op.drop_table('hv')
    op.drop_table('crtd')
    # ### end Alembic commands ###
